import os
import re
import subprocess
import sys
from llm_client import generate_manim_code, extract_python_code, save_code_to_file

def find_manim_class_name(code: str) -> str:
    """
    Scans the generated Python code using Regex to find the name of the 
    Manim Scene class so we know which class to render.
    """
    # Look for patterns like "class MyScene(Scene):" or "class MyScene( ZoomedScene ):"
    pattern = r"class\s+(\w+)\s*\(\s*\w*Scene\w*\s*\)\s*:"
    match = re.search(pattern, code)
    if match:
        return match.group(1)
    
    # Fallback to general class finder if "Scene" isn't explicitly in parentheses
    pattern_fallback = r"class\s+(\w+)\s*\("
    match_fallback = re.search(pattern_fallback, code)
    if match_fallback:
        return match_fallback.group(1)
        
    return "ExpandingBlueCircle"  # Default fallback

def run_manim_rendering(filepath: str, class_name: str) -> bool:
    """
    Executes the Manim compiler command as a Python subprocess.
    Equivalent to running: manim -pql filepath class_name in the terminal.
    """
    print(f"\n[Rendering] Compiling class '{class_name}' from '{filepath}'...")
    
    # -p: preview video when finished
    # -ql: low quality (renders lightning fast at 480p)
    command = [
        "manim", 
        "-pql", 
        filepath, 
        class_name
    ]
    
    try:
        # Run the command and stream output directly to VS Code terminal
        result = subprocess.run(command, check=True)
        if result.returncode == 0:
            print("\n[Rendering Success] Animation generated and opened successfully!")
            return True
    except subprocess.CalledProcessError as e:
        print(f"\n[Rendering Error] Manim compilation failed: {e}")
    except FileNotFoundError:
        print(f"\n[System Error] 'manim' command not found. Ensure Manim is installed in your virtual environment.")
    
    return False

def start_pipeline():
    print("==========================================================")
    print("      AI ANIMATION PLATFORM - FULL AUTOMATION PIPELINE    ")
    print("==========================================================")
    
    # 1. Ask user what they want to animate
    user_prompt = input("\nWhat educational animation would you like to build? ")
    if not user_prompt.strip():
        print("Empty input. Running default physics demo...")
        user_prompt = "Animate a projectile motion trajectory with a bouncing ball."
        
    # 2. Get code from Gemini
    raw_response = generate_manim_code(user_prompt)
    if not raw_response:
        print("[Error] Failed to get response from Gemini.")
        return

    # 3. Clean and parse code
    clean_code = extract_python_code(raw_response)
    
    # 4. Save the generated code to a file
    scene_file = "generated_scene.py"
    save_code_to_file(clean_code, scene_file)
    
    # 5. Dynamically extract the name of the Scene class generated by Gemini
    class_name = find_manim_class_name(clean_code)
    print(f"[Parser] Detected generated Scene class name: '{class_name}'")
    
    # 6. Render it automatically!
    run_manim_rendering(scene_file, class_name)

if __name__ == "__main__":
    start_pipeline()
